name: coastaltourism
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# Environment
environment:
  sdk: ">=3.0.0 <4.0.0" # Compatible with Dart 3.x and Flutter 3.x

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.4.0
  firebase_storage: ^12.3.4
  cloud_functions: ^5.1.3
  provider: ^6.0.0 

  # UI and animation packages
  action_slider: ^0.7.0
  salomon_bottom_bar: ^3.3.2
  animations: ^2.0.6
  rating_dialog: ^2.0.4
  flutter_email_sender: ^5.0.2
  

  # Maps and geolocation
  geolocator: ^13.0.1
  location: ^7.0.1
  google_maps_flutter: ^2.9.0
  google_places_flutter: ^2.0.6

  # Utility packages
  dio: ^5.7.0
  email_auth: ^2.0.0
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.8
  webview_flutter: ^4.0.1
  flutter_inappwebview: ^5.3.2
  # Additional plugins
  flutter_map_animations: ^0.7.1
  flutter_map_cancellable_tile_provider: ^3.0.2

  # Icons and fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1 # Optional. Remove if not needed.
  mailer: ^5.0.0
  http: ^1.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # For linting and best practices

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Uncomment and customize the following if you add custom assets:
  # assets:
  #   - assets/images/
  #   - assets/fonts/

  # Custom fonts configuration (optional)
  # Uncomment and update this section if you use local fonts
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
