// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCTaUe0KH02eoOU64tqFzZ5Oik06nAqFY',
    appId: '1:902969061647:web:05e8109d7a17163bd60e7a',
    messagingSenderId: '902969061647',
    projectId: 'fir-e22a4',
    authDomain: 'fir-e22a4.firebaseapp.com',
    storageBucket: 'fir-e22a4.appspot.com',
    measurementId: 'G-YR7RGPLY22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7hrmysH8ZyxZcIAGH6j3TcvW8o7hajtI',
    appId: '1:902969061647:android:88e8faa358549ff5d60e7a',
    messagingSenderId: '902969061647',
    projectId: 'fir-e22a4',
    storageBucket: 'fir-e22a4.appspot.com',
  );

}